Repository university-of-york/design-patterns, pull requests merged in 2018-07, with the labels that each got.

#6 Feature/json config data
  config/copy.js
  package-lock.json
  package.json
  src/data/globaldata.json
  src/js/app/clearing-table.js
  src/js/app/main.js
  src/js/app/utils.js
  src/opensearch.xml
  src/pages/01-layout/20-navigation.md
  src/pages/03-js-modules/35-clearing-tables-module.md
  src/templates/room-status/index.html
  src/templates/search-results/index.html
Labels: Code Review, Ready to Merge, enhancement

#9 Improve figure image width
  src/sass/component/_figures.scss
Labels: Code Review, Ready to Merge

#22 Fix/print stylesheets
  src/partials/head.mustache
  src/sass/print.raw.scss
  src/sass/print/_base.scss
  src/sass/print/_grid.scss
  src/sass/print/_resets.scss
  src/sass/styles.raw.scss
  src/templates/postgraduate/courses/music-education.html
  src/templates/undergraduate/courses/actuarial-science/index.html
  yarn.lock
Labels: Code Review, Ready to Merge, enhancement

#21 Fix: change the calculations on sticky nav
  src/js/app/main.js
  src/js/app/sticky-nav.js
  src/js/app/targeted-nav.js
Labels: Code Review, Ready to Merge, bug

#25 Update/sticky nav scroll
  src/sass/component/_key-fact.scss
  src/sass/component/_navigation.mobile.scss
  src/sass/print.raw.scss
  src/sass/print/_accordion.scss
  src/sass/print/_base.scss
  src/sass/print/_grid.scss
  src/sass/print/_resets.scss
  src/sass/styles.raw.scss
  src/templates/accommodation/rooms-prices/derwent/index.html
  src/templates/postgraduate/living-costs/index.html
Labels: Code Review, Ready to Merge, enhancement
