Repository university-of-york/design-patterns, pull requests merged in 2018-08, with the labels that each got.

#35 Fix/figure width
  src/sass/component/_figures.scss
  src/sass/object/_media.scss
  src/templates/postgraduate/courses/system-safety-engineering.html
  src/templates/research/themes/creativity/digital-creativity.html
Labels: Code Review, Ready to Merge

#39 Improve hcard on small screens
  src/sass/component/_hcard.scss
Labels: Code Review, Ready to Merge

#40 Prevent image zoom on small screens
  src/sass/core/_mixins.scss
Labels: Code Review, Ready to Merge

#43 Fix/modal overflow
  src/sass/component/_modal.scss
Labels: Code Review, Ready to Merge

#52 Add margin to the bottom
  src/sass/object/_media.scss
Labels: Code Review, Ready to Merge

#55 update: add Rollbar error reporting to repository
  config/jshint.js
  src/js/app.js
Labels: Code Review, Ready to Merge, enhancement

#56 Update map tiles
  src/js/app/google-map.js
Labels: Code Review, Ready to Merge

#61 fix: update Rollbar version
  src/js/app.js
  src/partials/assocnav.mustache
  src/partials/nav.mustache
  src/partials/subnav.mustache
Labels: Code Review, enhancement

#69 Fix/gallery modal image
  src/sass/component/_modal.scss
  src/templates/accommodation/rooms-prices/alcuin/index.html
Labels: Code Review

#71 Feature: data-grid and data-load api
  src/js/app.js
  src/js/app/data-firebase.js
  src/js/app/data-google-sheets.js
  src/js/app/data-grid.js
  src/js/app/globaldata.js
  src/js/app/main.js
  src/js/app/utils.js
  src/pages/03-js-modules/42-data-grid.md
  src/partials/assocnav.mustache
  src/partials/nav.mustache
  src/partials/subnav.mustache
  src/templates/client_secret.json
  src/templates/datagrids/firebase.html
  src/templates/datagrids/sheets.html
  src/templates/datagrids/sheetsapi.html
  src/templates/datagrids/sheetsapifirebase.html
  yarn.lock
Labels: Code Review, Ready to Merge, enhancement
